apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskbuddy-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskbuddy-app
  template:
    metadata:
      labels:
        app: taskbuddy-app
    spec:
      containers:
        - name: taskbuddy-app
          image: taskbuddy-app:placeholder
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5050
